apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: tech-share
  labels:
    app: auth-api
spec:
  ports:
    - port: 9200
      name: auth-api
      targetPort: 9200
  selector:
    app: auth-api
